"""Immutable run manifests, deterministic aggregation, and independent replay audit."""

from mtg_runs.manifests import (
    RunManifest,
    SeedAssignment,
    TestEvidence,
    build_manifest,
    load_manifest,
    validate_aggregation,
    write_immutable_run,
)
from mtg_runs.phase_c import (
    CONFIRMATION_TOKEN,
    EXPLORATORY_GAMES,
    EXPLORATORY_SHARDS,
    STANDARD_GAMES,
    STANDARD_SHARDS,
    PhaseCApproval,
    PhaseCConfiguration,
    PhaseCControlError,
    PhaseCDryRunReport,
    PilotSeedPlan,
    PilotShardAssignment,
    aggregate_phase_c_pilot_artifacts,
    build_pilot_seed_plan,
    build_pilot_shard_assignment,
    current_engine_blockers,
    dry_run_phase_c,
    execute_phase_c_pilot,
    execute_phase_c_shard,
    load_phase_c_approval,
    load_phase_c_config,
    validate_execution_authorization,
)
from mtg_runs.phase_c_artifacts import (
    PhaseCAggregateManifest,
    PhaseCGameArtifact,
    PhaseCShardManifest,
    validate_phase_c_aggregate,
)
from mtg_runs.replay_audit import (
    FreshProcessReplayResult,
    replay_in_fresh_process,
    verify_worker_invariance,
)

__all__ = [
    "CONFIRMATION_TOKEN",
    "EXPLORATORY_GAMES",
    "EXPLORATORY_SHARDS",
    "FreshProcessReplayResult",
    "PhaseCAggregateManifest",
    "PhaseCApproval",
    "PhaseCGameArtifact",
    "PhaseCConfiguration",
    "PhaseCControlError",
    "PhaseCDryRunReport",
    "PhaseCShardManifest",
    "PilotSeedPlan",
    "PilotShardAssignment",
    "RunManifest",
    "STANDARD_GAMES",
    "STANDARD_SHARDS",
    "SeedAssignment",
    "TestEvidence",
    "aggregate_phase_c_pilot_artifacts",
    "build_manifest",
    "build_pilot_seed_plan",
    "build_pilot_shard_assignment",
    "current_engine_blockers",
    "dry_run_phase_c",
    "execute_phase_c_pilot",
    "execute_phase_c_shard",
    "load_manifest",
    "load_phase_c_approval",
    "load_phase_c_config",
    "replay_in_fresh_process",
    "validate_aggregation",
    "validate_execution_authorization",
    "validate_phase_c_aggregate",
    "verify_worker_invariance",
    "write_immutable_run",
]
